### ISSUE TITLE
Rename menu breaks when regex refrencing ascii characters are used in .properties

### ISSUE THREAD

**Issue by AdeptusAutumn** [HiWord9/RPRenames-fabric#10]
Bit of an edgecase as I know of exactly one RP using this  ([Item Addon Pack](https://modrinth.com/resourcepack/item_addon), uses öäü) 
This RP uses regex to cover a lot of items and refrences öÖäÄüÜ by their ASCII codes in the regex

<img width="808" alt="image" src="https://user-images.githubusercontent.com/16197997/232566440-d591fa30-96ce-4ecb-b4af-b4942e287aba.png">

This is the line in the .properties for this item
`nbt.display.Name=iregex\:(.*\ |^)(Fl[\\u00D6\\u00F6]te|Flute)(\ .*|$)`

The Item in the image would be named "Flöte", though the regex would allow case INsesetive spelling as well as "Flute"

**Comment by HiWord9** [comment]
fixed in 0.7.0
