### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by dakfolz** [HiWord9/RPRenames-fabric#11]
I downloaded CIT Resewn and the mod still does not work, I don’t understand why, I clicked the “Done” item, but nothing works, the book icon in the anvil is just with a red stroke. I play on 1.19.2

![image](https://user-images.githubusercontent.com/131603313/233849988-8efba724-e0d7-468d-89eb-e57988cd729b.png)

**Comment by HiWord9** [comment]
Please check folder .minecraft/config, does it have subfolder "renames"? Is it empty? And tell me please which version of mod and what rps do use

**Comment by HiWord9** [comment]
Did u put an item into the slot? It shows renames for current item only. If it is not working, it should show u a message saying that there is no config for renames when u hovering the button.
If it does not working woth item too, please check folder .minecraft/config, does it have subfolder "renames"? Is it empty? And tell me please which version of mod and what rps do use

**Comment by dakfolz** [comment]
Ahh thank you, I'm just dumb
