### ISSUE TITLE
Add mod to modrinth website

### ISSUE THREAD

**Issue by DearFox** [HiWord9/RPRenames-fabric#12]
It looks like a good mod, but I, like many other people, are increasingly choosing to use modrinth as a mod download site.

**Comment by HiWord9** [comment]
Already in plans

**Comment by HiWord9** [comment]
Finaly did it! [Here is modrinth page](https://modrinth.com/mod/rp-renames)

**Comment by DearFox** [comment]
> Finaly did it! [Here is modrinth page](https://modrinth.com/mod/rp-renames)

It looks like you entered the wrong modrinth license.

![image](https://github.com/HiWord9/RPRenames-fabric/assets/59219907/5bffd3c5-7267-4331-bc14-6a470695a7a8)
![image](https://github.com/HiWord9/RPRenames-fabric/assets/59219907/60739d48-0f63-453a-9bbe-50d333c0bde3)

You can change it, as it affects the search, and your mod can be found using the checkbox "Open source only"

<3

**Comment by HiWord9** [comment]
Was confused, i will set the license to mit as **i have no idea** what does it mean but a lot of developers use it
