### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by dakfolz** [HiWord9/RPRenames-fabric#15]
In Russian, the inscription overlaps the "add to favorites" icon
![image](https://user-images.githubusercontent.com/131603313/234396327-7f6dde2d-3bf7-4915-8968-8dabb0855268.png)

**Comment by HiWord9** [comment]
I think this is not important issue. If i will work on it i will add ability to change button's position somehow

**Comment by HiWord9** [comment]
Now in 0.4.0! U can change its position in modmenu setiings, i recommend u to use preset  X-40 Y-60

**Comment by HiWord9** [comment]
Replaced option from exact coordinates to built-in presets in 0.9.0
