### ISSUE TITLE
Mod Conflict - Recursive Resources

### ISSUE THREAD

**Issue by GrandPappyJay** [HiWord9/RPRenames-fabric#17]
Minecraft 1.19.4 Quilt 0.18.10
When using RP Renames (0.2.1) along side Recursive Resources (2.4.1) the checkbox for "Recreate RPR config" is overlapping the "Open Pack Folder" button...  My guess is that Recursive Resources has moved the default button location...  It is possible to click your checkbox but only by selecting the far right 1 or 2 pixels...  Really only a minor inconvenience, but I thought I would share...  Thanks.

https://modrinth.com/mod/recursiveresources

![image](https://user-images.githubusercontent.com/55817923/236620252-8830f950-e630-4fd9-b372-0328692cad87.png)

**Comment by HiWord9** [comment]
Good comment. There are a few things that are overlaping some gui elements, like #15. I think i could make some button's positions optional in mod's settings, but it is not in mine current attention. If i will, i'ill fix it with adding mod's settings menu i guess

**Comment by HiWord9** [comment]
Btw, u can edit config/rprenames.properties for changing this setting if it is necessary

**Comment by HiWord9** [comment]
Now in 0.4.0! U can change its position in modmenu setiings
