### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by TRemill** [HiWord9/RPRenames-fabric#2]
![image](https://user-images.githubusercontent.com/69728227/230956463-9d9fa008-1a51-4965-9a35-fb81645dd93b.png)
 My modpack:
 [20:14:43] [main/INFO]: Loading 127 mods:
	- advanced-tooltips 1.6.0+1.19
	   \-- advanced-tooltips-core 1.6.0
	- ae2 12.9.2
	   |-- noindium 1.1.0+1.19
	   \-- team_reborn_energy 2.0.0-beta1
	- auudio 1.0.3
	- badpackets 0.2.1
	- betterf3 4.0.0
	- betterstats 2.4+1.19.2
	   \-- tcdcommons 2.4+1.19.2
	        \-- architectury 6.5.69
	- betterthirdperson 1.9.0
	- carpet 1.4.84
	- cloth-config 8.2.88
	   \-- cloth-basic-math 0.6.1
	- cpm 0.6.7a
	- creativecore 2.9.3
	- deathlog 0.2.11+1.19
	- drippyloadingscreen 2.1.2
	- emotecraft 2.2.5
	   |-- bendy-lib 2.1.2
	   \-- player-animator 0.3.5
	- entityculling 1.6.1-mc1.19.2
	- essential-container 1.0.0
	   \-- essential-loader 1.0.0
	- fabric-api 0.76.0+1.19.2
	- fabricloader 0.14.18
	- fancymenu 2.14.2
	- fancyvideo_api 2.0.1
	- ferritecore 5.0.3
	- fmextension_audio 1.1.1
	- fmextension_video 1.1.1
	- forgeconfigapiport 4.2.11
	   |-- com_electronwill_night-config_core 3.6.5
	   \-- com_electronwill_night-config_toml 3.6.5
	- healthoverlay 7.2.4
	   \-- fiber 0.23.0-2
	- iceberg 1.0.46
	- itemmodelfix 1.0.3+1.19
	- itemphysiclite 1.5.1
	- konkrete 1.6.0
	- lazydfu 0.1.3
	- legendarytooltips 1.3.3
	- litematica 0.12.7
	- malilib 0.13.0
	- minecraft 1.19.2
	- minihud 0.23.3
	- modmenu 4.1.2
	- mousetweaks 2.22
	- nbteditor 1.10.0
	- notenoughanimations 1.6.2
	- notes 1.19.2-2.0.0-fabric
	- optifabric 1.13.24
	   \-- mm 2.3
	- plasmo_voice 1.2.19
	- prism 1.0.3
	- puzzleslib 4.3.12
	   |-- cardinal-components-base 5.0.2
	   |-- cardinal-components-block 5.0.2
	   |-- cardinal-components-chunk 5.0.2
	   |-- cardinal-components-entity 5.0.2
	   \-- cardinal-components-world 5.0.2
	- replaymod 1.19.1-2.6.10
	- replayvoicechat 1.16+-1.1.0
	- rprenames 0.0.2
	   \-- libgui 6.4.0+1.19
	        \-- jankson 4.1.1+j1.2.1
	- shouldersurfing 2.3.0
	- smoothboot 1.19-1.7.1
	- spwallet 1.19.2-2.1.0
	   |-- blue_endless_jankson 1.2.1
	   \-- libninepatch 1.2.0
	- stylisheffects 4.3.3
	- watson 1.14.4
	- wildfire_gender 1.19-3.0.0
	- worldedit 7.2.12+6240-87f4ae1

**Comment by HiWord9** [comment]
Have u tryed to reload resource packs? Click Done button on pack selection screen, it should create the list of renames in config folder (will produce a little freaze). If u did, do u have folder "renames" in .minecraft/config? Is it empty?

**Comment by TRemill** [comment]
Yes, I have already reloaded resource packages. The folder was created and yes, it is empty.

**Comment by HiWord9** [comment]
Looks like i've miss some details in config creating part. Tell me please the name of this rp or mb link or sth

**Comment by HiWord9** [comment]
I thought for a minute, and mb i know why doesn't it work. Is the rp in zip?

**Comment by TRemill** [comment]
Here are 2 rp I'm playing with
https://www.curseforge.com/minecraft/texture-packs/newdefaultplus
https://www.curseforge.com/minecraft/texture-packs/bettervanillabuilding

**Comment by TRemill** [comment]
![image](https://user-images.githubusercontent.com/69728227/231205311-92d1ac4c-747b-45c8-bf00-d82928640698.png)
On the version 1.19.2 - 0.0.3 a file was created, but no more, there are no further effects.

**Comment by HiWord9** [comment]
> 

Got the same, but i have progress. Seems like i have to change config creating a lot. I was testing only with ksepsp and few others, and it worked perfect

**Comment by HiWord9** [comment]
Fixed in 0.0.4. There are different possible names for values storing item's name: "matchItems" and "items". I wasn't know about that, and mod was ignoring "items" value. That's the deal
