### ISSUE TITLE
Error \ improvement: Other nbt tags are not taken into account

### ISSUE THREAD

**Issue by DearFox** [HiWord9/RPRenames-fabric#20]
In my resource pack, in terms of changing the texture, in addition to renaming, the signature of the item is also taken into account, I think it’s worth adding a handler for other nbt that are required for renaming and notify the user of their need
![image](https://github.com/HiWord9/RPRenames-fabric/assets/59219907/6e06d859-66fb-4764-aa06-8911bf36e16e)

**Comment by HiWord9** [comment]
Added support for tags as Enchantment Damage StackSize in 0.7.0
