### ISSUE TITLE
searches are case-sensitive

### ISSUE THREAD

**Issue by ryleu** [HiWord9/RPRenames-fabric#23]
When searching for "chair", "Chair" does not show up.

"chair"
![image](https://github.com/HiWord9/RPRenames-fabric/assets/69326171/aff96d36-51c7-4a71-b39c-9a41a184ef41)

"Chair"
![image](https://github.com/HiWord9/RPRenames-fabric/assets/69326171/f2671b27-79f1-4489-bdfe-f454234c8533)

Searches should be case-insensitive for usability.

**Comment by HiWord9** [comment]
I'm about to make it works in next update. Btw, u can use "*" char if it neccesary. Like if u type "*hair" it will show u every rename that contains "hair" including "Chair" and "chair"

**Comment by HiWord9** [comment]
Fixed in 0.5.0 😎
![deleted screenshot lol](https://cdn.modrinth.com/data/hvqcuDMT/images/70784a4ef264d89f6cc86db8563cba5bec606e17.png)
Screenshot from modrinth
