### ISSUE TITLE
Incompatable with Creative Core

### ISSUE THREAD

**Issue by JormTheProto** [HiWord9/RPRenames-fabric#24]
With CreativeCore and this mod installed, the game crashes upon launch. I attached a crash log with more details.

this mod is very promising and will definitely be a must have, but right now its a compatability and crash nightmare. It Works On My Machine™ but still.
[crash-2023-07-01_10.47.08-client.txt](https://github.com/HiWord9/RPRenames-fabric/files/11925216/crash-2023-07-01_10.47.08-client.txt)

**Comment by JormTheProto** [comment]
Unrelated to the issue but it would be nice if the mod had a mini hud option, with rename options displayed in a 5x4 grid akin to the vanilla crafting guide, with the names appearing when hovering over.

**Comment by HiWord9** [comment]
> Unrelated to the issue but it would be nice if the mod had a mini hud option, with rename options displayed in a 5x4 grid akin to the vanilla crafting guide, with the names appearing when hovering over.

Bro u are reading my mind, i'm about to add a grid mode in 0.6.0 instead of [fullscreen mode](https://github.com/HiWord9/RPRenames-fabric/wiki/Plans-and-other) , because im adding new tab with a lot of renames and thought that it would be a lot easyer if there would be fewer pages

**Comment by HiWord9** [comment]
> With CreativeCore and this mod installed, the game crashes upon launch. I attached a crash log with more details.
> 
> this mod is very promising and will definitely be a must have, but right now its a compatability and crash nightmare. It Works On My Machine™ but still. [crash-2023-07-01_10.47.08-client.txt](https://github.com/HiWord9/RPRenames-fabric/files/11925216/crash-2023-07-01_10.47.08-client.txt)

I've checked the log file and more likely it wont be a problem in 0.5.0 that is comming out rn, wi'll see soon

**Comment by HiWord9** [comment]
[RP Renames 1.19.4-0.5.0](https://modrinth.com/mod/rp-renames)
![2023-07-02_06 01 14](https://github.com/HiWord9/RPRenames-fabric/assets/46609661/165417df-1caa-43ca-9eb6-b429b254756f)
![2023-07-02_06 01 17](https://github.com/HiWord9/RPRenames-fabric/assets/46609661/d03699f2-8b53-4320-9a36-ab8fa3a73df1)
