### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by its-simple-as-that** [HiWord9/RPRenames-fabric#25]
The mod fails to work with Wildcards(*, ?):

'?' is used in Optifine to denote that any character can be here.
Example: "Hello ?????" would **work with 'Hello World', 'Hello There' and 'Hello      '** but _not 'Hello there!' or 'Hello here'_.
'*' is used in Optifine to denote that any set of words can exist on the unspecified side.
Example: "Hello *" would work with 'Hello World' and 'Hello There!' but not 'HelloThere!' or 'Hello'
               "*, Hey!" would work with 'Herobrine, Hey!' but not 'Herobrine , Hey!' (Space before comma) or 'Hey, Herobrine'

These do not play well with this mod. Files and images will be shared below.
Suggested (?):
![suggested](https://github.com/HiWord9/RPRenames-fabric/assets/87000530/814daf55-c4f0-4216-9b10-c46513a06b25)
What I Gave (?):
![what_i_got](https://github.com/HiWord9/RPRenames-fabric/assets/87000530/cc20d4d5-dc77-41b4-85d2-ba58bf0f5dc8)
What It Should Suggest/Try to (?):
![what_i_was_supposed_to_get](https://github.com/HiWord9/RPRenames-fabric/assets/87000530/f69eed9f-9312-4978-a342-2edfb5b852de)
What Is Suggested and works (*):
![the_asterisk_suggested](https://github.com/HiWord9/RPRenames-fabric/assets/87000530/75e47438-f1d6-46ad-9b2b-95591b1746a1)
What also works:
![this_works_ok](https://github.com/HiWord9/RPRenames-fabric/assets/87000530/e3992ed3-b690-4457-80ed-11d57f593491)

the '?' wildcard in photo
type=item
items=paper
nbt.display.Name=ipattern:KC?

the '*' wildcard in photo
type=item
items=bundle shulker_box
nbt.display.Name=ipattern:*CardBox

**Comment by its-simple-as-that** [comment]
The asterisk works fine but wildcard could use some tweaking.

**Comment by HiWord9** [comment]
Will fix it in next update.
Btw the "\*" symbol is specially ignored because rename works fine without it.
I was planned to make a debug setting to show original nbt.dislay.Name value in tooltip for cases if bug like this will be triggered, and now im thinking about making extra info like "u can write anything at the end of this rename" in tooltip

**Comment by its-simple-as-that** [comment]
Yes, Your Idea would solve the problem.

**Comment by HiWord9** [comment]
fixed in 0.7.0
