### ISSUE TITLE
matchItems=minecraft:

### ISSUE THREAD

**Issue by GrandPappyJay** [HiWord9/RPRenames-fabric#3]
A config file is not generated if the CIT properties file contains "matchItems=minecraft:coal" but works just fine for "matchItems=coal"...  It doesn't seem to want to read the "minecraft:"

Testing in 1.19.4.0.0.3

**Comment by HiWord9** [comment]
Thank for report! I know why it is and i will fix it in next beta versions. I wont close the issue untill fix the bug

**Comment by HiWord9** [comment]
Now it works in 0.0.4
