### ISSUE TITLE
Nothing's gonna show up

### ISSUE THREAD

**Issue by cookie981** [HiWord9/RPRenames-fabric#30]
minecraft 1.20.1
quilt_loader-0.20-beta.11
mod list:qfapi-7.1.0_qsl-6.1.0_fapi-0.86.1_mc-1.20.1.jar,RPRenames-1.20.x-fabric-0.6.0.jar,cloth-config-11.1.106-fabric.jar
resourcepacks:NewDefault+v1.68[MC1.20-1.20.1].zip[https://legacy.curseforge.com/minecraft/texture-packs/newdefaultplus](url)
![image](https://github.com/HiWord9/RPRenames-fabric/assets/83451181/e8c3e6e8-8bef-42dc-a778-1b6af2925f8b)
I don't know if it's a package error or a mod error. Can you fix it? I really like your mod.😘

**Comment by HiWord9** [comment]
i'd like to see the logs, please send the file here

**Comment by cookie981** [comment]
[latest.log](https://github.com/HiWord9/RPRenames-fabric/files/12328597/latest.log)


> i'd like to see the logs, please send the file here

**Comment by cookie981** [comment]
It's been solved. It's the quilt loader being too new. Sorry

**Comment by HiWord9** [comment]
> It's been solved. It's the quilt loader being too new. Sorry

I hope it is, otherwise i should check all cases why it is broken, and i still should do it, cause i have to be sure that is it the root of its issue and nothing else. Anyways thanks for reminding me about a problem
