### ISSUE TITLE
Crashes on load in 1.20.1

### ISSUE THREAD

**Issue by NezzleGod** [HiWord9/RPRenames-fabric#31]
https://pastebin.com/JuMQi0pu - Crash report

When opening minecraft, it instantly crashes with error code -1. If i disable or delete the mod, it works fine. It was also working before i deleted Entity Texture Features mod. I don't know if mods connected or not.

**Comment by HiWord9** [comment]
I'ill try to solve it in next updates, but i couldn't reproduce the bug so for now i fully not sure what is causeing it. Very interesting that the Entity Texture Features mod prevents the game from crashing, are u sure that with this mod installed the game is not crashing? In this case i recommend u too install this mod (and Entity Model Features as well cause they are made for each other)

**Comment by HiWord9** [comment]
fixed in 0.7.0
