### ISSUE TITLE
Rp renames not using whole names after renaming and showing different Items bc of that

### ISSUE THREAD

**Issue by Snipperly** [HiWord9/RPRenames-fabric#32]
I saved and cannot delete it lmao ty tho

**Comment by HiWord9** [comment]
So no problem here? Just a mistake?

**Comment by dima-dencep** [comment]
Хиворд даун

**Comment by Snipperly** [comment]
Yes sorry we figured that the 1.20 texture pack is not working so we switched her back to an older version which fixed it! Sorry to bother tho! c:
