### ISSUE TITLE
Mod does not show Modded Item renames 

### ISSUE THREAD

**Issue by V-lpen** [HiWord9/RPRenames-fabric#33]
https://i.imgur.com/kt7HcgV.png

I made a tiny mod that adds a placeholder item for CIT and it all displays fine (with the additional textures being in the /minecraft folder in a resource pack), but RP Renames doesnt recognize it. 

I can confirm its not detecting a modded item because the moment i changed one of the CIT items to a vanilla item it displayed it immediately

**Comment by HiWord9** [comment]
Thanks for report! I know about it, it is already in [plans](https://github.com/HiWord9/RPRenames-fabric/wiki/Plans-and-other), and I know how to fix it.

**Comment by V-lpen** [comment]
oh thank you! i look forward to this, it will help me out a lot. thank you so much for making this cool mod!

**Comment by HiWord9** [comment]
added support for non-minecraft items in 0.7.0
