### ISSUE TITLE
asking

### ISSUE THREAD

**Issue by verixyt3** [HiWord9/RPRenames-fabric#35]
Please do as much as you can mod for 1.20.2 on modrinth

**Comment by dima-dencep** [comment]
NeoForge 1.20.2 when

**Comment by HiWord9** [comment]
Mod will be ported on 1.20.2 as fast as 0.7.0 version itself will be finished. I'm not planning to port current 0.6.0 version on 1.20.2 cause I've changed a lot and it just have almost no sense. So I'll release 0.7.0 with its port on 1.20.2

**Comment by HiWord9** [comment]
> NeoForge 1.20.2 when

tomorrow

**Comment by verixyt3** [comment]
and it's not soon? (0.7.0)

**Comment by HiWord9** [comment]
> and it's not soon? (0.7.0)

It will be out very very soon

**Comment by verixyt3** [comment]
you can mod 1.20.2 on modrinth, as I understand 0.7.0 came out, but I don't understand which version to compile
![image](https://github.com/HiWord9/RPRenames-fabric/assets/138714269/fd2563c4-e7bc-453e-8f33-3e6a340344ab)

**Comment by HiWord9** [comment]
nah I haven't made it I'm lazy

**Comment by gaussandhisgun** [comment]
> nah I haven't made it I'm lazy

well its time to start working on it now 👀

**Comment by HiWord9** [comment]
> > nah I haven't made it I'm lazy
> 
> well its time to start working on it now 👀 

Actually, I would very like to get to work as fast as I can, especially after 1.20.3 and 1.20.4 came out. But unfortunately rn I'm in state when coding anything just forces me to feel bad, like I'm tired tbh. Good news that I'm starting to getting back very slowly, and I think I could do all stuff I wanted, including port to latest version, at the end of December or at the begging of January.

**Comment by HiWord9** [comment]
check modrinth
![image](https://github.com/HiWord9/RPRenames-fabric/assets/46609661/566b5a1d-3e4c-4429-b456-d4a592965c0b)
