### ISSUE TITLE
Shared Resources support

### ISSUE THREAD

**Issue by KlashRaick** [HiWord9/RPRenames-fabric#39]
https://modrinth.com/mod/shared-resources
Сделать поддержку иной папки с подгружаемыми ресурспаками, если такое возможно.
У меня например не подхватываются различные предметы по переименованию, т.к. кастомный путь к папке с ресурспаками.

**Comment by HiWord9** [comment]
Дубликат #27.
Либо сделаю автоматически либо на основе ручной настройки. Не в приоритете
