### ISSUE TITLE
Wildcards

### ISSUE THREAD

**Issue by GrandPappyJay** [HiWord9/RPRenames-fabric#4]
When generating the config file for each item the mod seems to pull everything on the right side of the ":" as the name instead of reading the format as intended by the .properties writer... 

For example:
nbt.display.Name=ipattern:\*Diamond Sword Stuck\*  becomes  \*Diamond Sword Stuck\*  instead of  Diamond Sword Stuck...

This may be entirely as intended but since the name now doesn't match the predicate expected name the proper CIT texture/model isn't loaded... 

![image](https://user-images.githubusercontent.com/55817923/231026224-1baf3981-a5e9-4f12-ae03-a2ab3798d410.png)

Testing with 1.19.4.0.0.3

**Comment by GrandPappyJay** [comment]
The * in the comment above worked as formatting instead of text... ugh...

**Comment by HiWord9** [comment]
Thanks for report! Actually, i wasn't know how does ipattern works. Will fix that in future updates, for now the issue is open.
*Achievement unlocked: bug hanter*

**Comment by HiWord9** [comment]
Added "ipattern:", "regex" and all others tags support in 0.0.4
