### ISSUE TITLE
Crashing After 150th page in the list

### ISSUE THREAD

**Issue by avro170** [HiWord9/RPRenames-fabric#41]
Crashing after 150th page on 1.20.1, guess it reaches some kind of a limit
Крашит после 150 страницы на версии 1.20.1, думаю ему мешает какое-то ограничение

**Comment by HiWord9** [comment]
Please tell me which resource packs u was using when this issue accured, and also i would like to see log file
Какие ресурспаки были активны? Хотелось бы со ссылками если их много. И скинь пж файл логов сразу после краша, этот файл находится в .minecraft/logs/latest.log

**Comment by avro170** [comment]
i was using this resource pack https://drive.google.com/file/d/15B3_IPU8qnNVt-uDZicmU2IW5IaZmgRa/view?usp=drive_link
[latest.log](https://github.com/HiWord9/RPRenames-fabric/files/13469647/latest.log) logs

**Comment by HiWord9** [comment]
Fixed in 0.7.1
