### ISSUE TITLE
Request: "Compact multiple matches" option

### ISSUE THREAD

**Issue by frugbug** [HiWord9/RPRenames-fabric#42]
I'm making a resource pack, and for player convenience I match most CITs to several items. For example, I have a custom wall lantern object that matches `lantern` as well as `torch` and several other items. This appears in the list as multiple entries, as you can see with lots of items here:
![image](https://github.com/HiWord9/RPRenames-fabric/assets/67615785/aa2aa738-c261-4d0a-81ca-a3f9ac29d7ff)
![image](https://github.com/HiWord9/RPRenames-fabric/assets/67615785/effab549-736a-43f1-b60a-4017fa745042)

I'd like to request an option to minimise the clutter that results from this. Perhaps, when enabled, this option could cause all the entries in the list to be compacted, with multiple items listed in the item's popup text. Something like this quick mockup:
![image](https://github.com/HiWord9/RPRenames-fabric/assets/67615785/70e52bbd-7b24-4708-bc20-5bec9392d424)
I hope I did a decent job explaining the concept, and that this might be possible. Thanks a lot!

**Comment by HiWord9** [comment]
I was thinking about it, that it is so common and necessary. I will be thinking about this feature more, most likely it will be added some day. I like ur representation of it, not sure if it will looks like it, mb. Thanks for ur suggestion!

**Comment by HiWord9** [comment]
now in 0.8.0
