### ISSUE TITLE
GUI Click Sounds

### ISSUE THREAD

**Issue by Imabanana80** [HiWord9/RPRenames-fabric#43]
not really an issue but idk where to ask this,

When clicking around the CIT GUI there arent any click sounds which feels really weird. Not an important feature by an means but would be nice to have.

**Comment by HiWord9** [comment]
The sound goes with default minecraft's widgets, i am using my own in purpose of flexability. I didn't implemented sound on click because i desided it is not neccessary.
**Mb** i will add the sound back somewhen
