### ISSUE TITLE
Minecraft 1.20.4 support

### ISSUE THREAD

**Issue by latipun7** [HiWord9/RPRenames-fabric#46]
Please add support for fabric MC 1.20.4 🙏 Currently this mod won't launch on that version.

**Comment by EXOgreen** [comment]
CIT-Resewn hasn't updated to 1.20.4, which this mod requires.

Now, that being said, there is a fork that does work and could be used as a basis to update this mod. I've been using it for 20+ hours and found no issues.

https://github.com/dicedpixels/CITResewn/tree/1.20.4-1.1.4-dicedpixels

**Comment by latipun7** [comment]
Yep, that's the CIT mod that I use too. I forgot that original CIT-Resewn not updated to 1.20.4 yet, that's why I ask this mod to update to 1.20.4.
Thank you🙏

**Comment by HiWord9** [comment]
In case someone would like to port rpr to 1.20.4 by self and pr this project: more likely i will refuse pr cause im already working on an update and official 1.20.4 port seems to be soon already with update im working on.

Im especially talking about a few recently created forks like [this one](https://github.com/latipun7/RPRenames-fabric) by @latipun7 and [this one](https://github.com/AlekzDan/RPRenames-fabric) by @AlekzDan.

U may try and use 0.7.2 ported by urself in case when u finish i will be still working on an update, but i believe u will spend ur time not as efficient as it would be

**Comment by HiWord9** [comment]
omagad citresewn 1.20.4 just released i have to hurry up

**Comment by HiWord9** [comment]
check modrinth
![](https://private-user-images.githubusercontent.com/46609661/296517108-566b5a1d-3e4c-4429-b456-d4a592965c0b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE5NTcwNjUsIm5iZiI6MTcxMTk1Njc2NSwicGF0aCI6Ii80NjYwOTY2MS8yOTY1MTcxMDgtNTY2YjVhMWQtM2U0Yy00NDI5LWI0NTYtZDRhNTkyOTY1YzBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAxVDA3MzI0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA0MWFiY2VlMjdhOWE3NmFlZmVmNjk4ZTA1OTc5NWNmZTM0NGEzMGVkYzg0MzI3ZmQyZjY5MzBmODQ5OWJjZGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jVrEmajFUWPjPHR-UAtpghjhx7cfeClcQ20DqvDwVQI)

**Comment by HiWord9** [comment]
not a joke if anything
