### ISSUE TITLE
Conflict with .jpm

### ISSUE THREAD

**Issue by GrandPappyJay** [HiWord9/RPRenames-fabric#51]
Minecraft 1.20.4 & RP Renames 0.8.0-1.20.4 
ETF 5.2, EMF 1.4, Fabric API 0.96.11+1.20.4
Excalibur 1.20.4, Fresh Animations 1.9, Excalibur | Fresh Animations Build 6
Everything listed should be the latest publicly available.

RP Renames seems to have a conflict with .jpm files in CEM.  Fresh Animations support packs are built mostly from .jpm files to expand on FreshLX's pack and abide by Terms.  If I remove all of the .jpm files from E|FA then everything will load properly but with the .jpm files present the game will unload all packs.  I replicated this with multiple .jpm files to confirm it wasn't just and issue with a specific file.

Very glad to see this got updated!  If you need anything more please let me know.

**Comment by HiWord9** [comment]
fixed in 0.8.1 !
Thanks for your feedback!
![2024-04-01_22 55 51](https://github.com/HiWord9/RPRenames-fabric/assets/46609661/e4fe0275-6e3c-4679-ad2c-5b436e74d18b)
