### ISSUE TITLE
Previewing the wrong texture with elytras

### ISSUE THREAD

**Issue by gorkareplay** [HiWord9/RPRenames-fabric#52]
My resource pack has two elytras, both have two textures, one for the broken version(damage = 431) and one for the non-broken one. When using this mod with my resource pack in the menu the preview for the elytra shows the broken version by default. Is there a way I can overwrite that?

**Comment by HiWord9** [comment]
i would like to see the pack, please send it here

**Comment by HiWord9** [comment]
Im pretty sure in ur case the menu should display both variant, the broken one and the one with full durability. The only thing i noticed that there wont be broken variant in menu if the property file for ``type=item`` specifies both ``texture.elytra=texture`` and ``texture.broken_elytra=broken_texture`` in one file

**Comment by gorkareplay** [comment]
Here is the resource pack
[PlayerThingsPaperBin.zip](https://github.com/HiWord9/RPRenames/files/15141061/PlayerThingsPaperBin.zip)

**Comment by HiWord9** [comment]
So i took a look at ur pack and found out what causes it.
RPR wont add another rename to list if there is the same rename or same but with **some values not assigned**. In ur case u made one rename with ``damage=431`` and another without ``damage`` property at all, rpr treats second one as already assigned and does not adds it to list. 

There are a few ways to list the full durability rename:
1. U can add to unbroken property file parameter ``damage=0-430``, in this case both broken and unbroken variants will be treated as different renames.
![image](https://github.com/HiWord9/RPRenames/assets/46609661/20e63c21-0fbc-4426-952f-8ba6ab0ac34e)

2. U can make **one property file** for both broken and intact variants the way i described [here](https://github.com/HiWord9/RPRenames/issues/52#issuecomment-2081230799), all u need is just to make two ``texture`` parameters in one property file, ``texture.elytra=texture`` and ``texture.broken_elytra=broken_texture``, and u do not need ``damage`` anymore. This way is the best, as it is intended and there wont be broken variant in list, what i think better than seeing both.
![image](https://github.com/HiWord9/RPRenames/assets/46609661/ce8a4a34-e8c6-440e-8abf-24e1d5af7dac)
![image](https://github.com/HiWord9/RPRenames/assets/46609661/fe086656-81b7-49a1-a6ff-dc8f1860a145)


Mb i could make feature where rename will tell if it has broken variant in tooltip in future, but it is not in plans and not neccessary for now.
Hope i helped u with ur pack!
