### ISSUE TITLE
CEM name tag variants show up in RPRenames for some resource packs but not others

### ISSUE THREAD

**Issue by Jeremiah623** [HiWord9/RPRenames-fabric#54]
Minecraft 1.20.4 & RP Renames 0.8.2-1.20.4
ETF 5.2.3, EMF 1.3 Fabric API 0.96.11+1.20.4

Nametag variants of mobs show up in the anvil menu when using certain resource packs like [Recrafted Mobs](https://modrinth.com/resourcepack/recrafted-mobs) or [Assorted Allays](https://modrinth.com/resourcepack/assorted-allays), but for some reason nametag variants for resource packs like [Cluckier Chickens](https://www.curseforge.com/minecraft/texture-packs/cluckier-chickens), or [Al's Allay Pack](https://www.curseforge.com/minecraft/texture-packs/als-allay-pack) don't show up.
I'm using Fresh Animation addons for some resource packs like Cluckier Chickens and Al's Allay Pack, but when I tested out using the base versions without the addons they didn't show up in the anvil menu either.

My best guesses are that it might have something to do with resource pack versions not being updated to the current version (1.20.4) or maybe that the mod doesn't recognize models that are compatible with Fresh Animations.

**Comment by HiWord9** [comment]
Found out what the problem: rpr looks for cem renames partly in optifine/cem dir and partly in optifine/random dir, the root of issue is that these ignored packs does not use optifine/random folder but optifine/mob
![image](https://github.com/HiWord9/RPRenames/assets/46609661/175cc6c7-cfa1-4fae-9a48-96fa905fe80d)
I'll try to fix it in next version, i will note here if anything else causes the problem too
thx for letting me know!

**Comment by Jeremiah623** [comment]
Np, thanks for the response!

**Comment by aurora-1-2-3** [comment]
based examples (packs)
