### ISSUE TITLE
Minecraft crash when switching pages with pumpkin renames.

### ISSUE THREAD

**Issue by ImAvairus** [HiWord9/RPRenames-fabric#56]
I have a resourcepack with a bunch of renames for a carved pumpkin. When i turn the page MC crashes. In the "global" page, when i swap, MC crashes on 11th page.
Issue is in resourcepack, some item chashing the game when attempting to render it. But i dont think that it should be like it, so i reporting this here. Log is pinned
[latest.log](https://github.com/user-attachments/files/15838043/latest.log)
[ShrimpS pack [1.9].zip](https://github.com/user-attachments/files/15838048/ShrimpS.pack.1.9.zip)
pinned video with issue shown: (it's on russian, shouldn't be an issue)
https://github.com/HiWord9/RPRenames/assets/163941214/111334e2-fec7-4535-aa10-b48cf8e471e8

1.20.1, mod version 0.8.2, fabric 0.15.11

**Comment by HiWord9** [comment]
Checked on the latest dev build, found no problem. I will close the issue after publishing the next stable build.
