### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by GrandPappyJay** [HiWord9/RPRenames-fabric#6]
After updating to the latest version (1.19.4.0.1.1) of RP Renames my game crashes on load.  

[latest.log](https://github.com/HiWord9/RPRenames-fabric/files/11239100/latest.log)

**Comment by HiWord9** [comment]
Fixed in 0.1.1.1. My bad, this is very stupid bug

**Comment by GrandPappyJay** [comment]
Works great!!  Thank you!
