### ISSUE TITLE
1.21 crash When opening the anvil

### ISSUE THREAD

**Issue by Ramadhn16** [HiWord9/RPRenames-fabric#62]
Whit crash log:
mouseClicked event handler

java.lang.NullPointerException: Cannot invoke "com.HiWord9.RPRenames.util.gui.widget.button.external.OpenerButton.method_25402(double, double, int)" because "this.opener" is null

**Comment by HiWord9** [comment]
One line of logs is not enougth, please send whole file and reopen the issue

**Comment by Ramadhn16** [comment]
Complete crash log is here:
https://github.com/Ramadhn16/Minecraft-issue-/blob/main/crash-2024-09-27_15.19.18-client.txt

**Comment by Ramadhn16** [comment]
I use pojav, because I don't have a computer/PC

**Comment by Ramadhn16** [comment]
I use pojav, because I don't have a computer/PC

**Comment by Ramadhn16** [comment]
Sorry, I'm new to this kind of problem so I don't really understand😅

**Comment by Ramadhn16** [comment]
Sorry, I'm new to this kind of problem so I don't really understand😅

**Comment by HiWord9** [comment]
Incompatibility with easy anvils, duplicate of #14. If u want to use rprenames u should uninstall easy anvils.

**Comment by Ramadhn16** [comment]
Thanks, it worked😁👍
