### ISSUE TITLE
Incompatibily with LegendaryTooltips on 1.20.4

### ISSUE THREAD

**Issue by Clownarchy** [HiWord9/RPRenames-fabric#63]
Minecraft 1.20.4 on Fabric (Loader Version 0.16.2), Easy Anvils is not installed. This issue is on a multiplayer server with a data pack that has several CIT reskin items.

When opening the book in an empty anvil, it immediately crashes. If there is an item in the anvil it doesn't immediately crash, but clicking on the global option did crash my game.

Note: I saw this https://github.com/HiWord9/RPRenames/issues/61 and it looks similar, unfortunately all my mods in this pack are currently up to date.

Log:
[crash-2024-10-21_04.37.28-client.txt](https://github.com/user-attachments/files/17459372/crash-2024-10-21_04.37.28-client.txt)

**Comment by Clownarchy** [comment]
Definitely seems to be an incompatibility between Legendary ToolTips & RP Renames, unfortunately I don't have the option of updating the mods here. Any suggestions?

**Comment by HiWord9** [comment]
Incompatibily with old version of Legendary Tooltips. Sadly, LT's newest version for 1.20.4 is 1.4.5 which is lower than compatible version (1.4.11). I do not plan to maintain old minecraft versions, RPR went to 1.21 recently and wont be getting updated for versions <1.21, as 1.20.4. U need to remove either RPR or LT to fix ur modpack.

**Comment by HiWord9** [comment]
But actually there is a thing that can help u: rprenames have a bunch of chat commands, u can list renames for some item by ``/rprenames list`` for item in hand or same with item tag for this specific item. U can also make buttons not appear in anvil menu in mod's config: modmenu -> rprenames -> settings -> general -> show rprenames button -> off
