### ISSUE TITLE
Button Text

### ISSUE THREAD

**Issue by GrandPappyJay** [HiWord9/RPRenames-fabric#7]
Yeah, It's me again...  Sorry about keeping your issue list from being empty...

What about setting the text to be left justified (instead of centered) with just a small space off of the item box?
On the right side the text could be ignored beyond a certain character limit to keep the button looking nice...

![image](https://user-images.githubusercontent.com/55817923/232225367-be946429-04d1-4598-8839-3ff27e8de5bf.png)
![image](https://user-images.githubusercontent.com/55817923/232225778-8dea50e1-be9c-402d-8320-0f0a3af136a5.png)

All the "B" would be aligned on the left side
![image](https://user-images.githubusercontent.com/55817923/232225694-d58a58ad-9d53-462f-9385-226403a8a5e2.png)

**Comment by GrandPappyJay** [comment]
For really long names my idea could be troublesome though...  I wonder if there is a way to allow the text to scroll across the button when it is highlighted...  

I really like the potential of this mod!

**Comment by HiWord9** [comment]
> Yeah, It's me again... Sorry about keeping your issue list from being empty...

No need to excuse, this issues made me working on mod a lot, and without them i would notice bugs very lately

**Comment by HiWord9** [comment]
Came with this solution:
![image](https://user-images.githubusercontent.com/46609661/232261615-04f54f7b-5614-419b-ae94-c353ea8d1fc3.png)
Will be added in 0.1.2

**Comment by GrandPappyJay** [comment]
Looks much better!
