### ISSUE TITLE
 Crash on pressing done in Resource pack menu

### ISSUE THREAD

**Issue by AdeptusAutumn** [HiWord9/RPRenames-fabric#8]
[latest.log](https://github.com/HiWord9/RPRenames-fabric/files/11242925/latest.log)
[crash-2023-04-16_18.59.41-client.txt](https://github.com/HiWord9/RPRenames-fabric/files/11242928/crash-2023-04-16_18.59.41-client.txt)
Added the mod. Restartet game. Opend Resource pack menu from Main menu. Pressed Done. Got "Saving World". Crash

**Comment by HiWord9** [comment]
Which Minecraft version?

**Comment by HiWord9** [comment]
Nvm. Give me please all links for Ur resource packs which have cits

**Comment by AdeptusAutumn** [comment]
Minecraft 1.19.2

CIT
https://www.curseforge.com/minecraft/texture-packs/xalis-enchanted-books
https://www.curseforge.com/minecraft/texture-packs/visual-shulker-labels
https://www.curseforge.com/minecraft/texture-packs/visual-shulker-labels-2d-display-addon
https://www.curseforge.com/minecraft/texture-packs/bettervanillabuilding-custom-item-edition
https://modrinth.com/resourcepack/item_addon
Only 2 CIT .properties located at resourcepacks\Autumns Tweaks\assets\minecraft\optifine\cit\armorsets\davinci: [elytraitem.properties](https://pastebin.com/KvWzCuFw), [elytra.properties](https://pastebin.com/p5A5x1p9)

Chime
https://www.curseforge.com/minecraft/texture-packs/invisible-armor-for-players-only

**Comment by HiWord9** [comment]
_Fixed_ in 0.1.3
