### ISSUE TITLE
Can`t load RP with Optifabric and crash

### ISSUE THREAD

**Issue by MarryBye** [HiWord9/RPRenames-fabric#9]
I can`t load any RP from list, when installed Optifabric + Optifine on 1.19.4. Without the mod all works good.
But with Sodium + CIT Resewn all works good with mod.

Used latest versions of mod 0.1.3 and 0.1.2.

**Comment by MarryBye** [comment]
https://www.curseforge.com/minecraft/mc-mods/optifabric/files/4455920 - Optifabric

https://www.optifine.net/downloads - Optifine HD U I4

**Comment by HiWord9** [comment]
Send there please latestlog.txt and crash log if it doesn't bother you

**Comment by HiWord9** [comment]
Which rps u have used? Are u sure u used rps with compatible version for 1.19.4?

**Comment by HiWord9** [comment]
Looks like mod incompatible, on 1.19.2 all works fine. should be remembered, that this optifabric version is beta. We'll see later is it or not

**Comment by HiWord9** [comment]
works fine again on 1.20.2 🤔🤨
![image](https://github.com/HiWord9/RPRenames-fabric/assets/46609661/48d9492b-d94b-41b6-9230-0bf67e7fed17)
